production:
    app_function: application.app
    aws_region: us-east-1
    exclude:
      - .gitignore
      - __pycache__
      - LICENSE
      - node_modules
      - package*.json
      - prepros-6.config
      - requirements.txt
      - static
      - zappa_settings.yml
    log_level: WARNING
    profile_name: default
    project_name: technologist
    runtime: python3.6
    s3_bucket: anthonyschwartzman.net-zappa
